- name: Install RADIUS to Debian
  hosts: debian
  become: yes
  become_method: su

  tasks:
  - include_vars: "./vars.yml"
  - name: Install dependency
    apt:
      name:
        - samba-dsdb-modules
        - samba-vfs-modules
        - winbind
        - libpam-winbind
        - libnss-winbind
        - libpam-krb5
        - krb5-config
        - freeradius
        - freeradius-common
        - freeradius-krb5
        - freeradius-ldap
        - freeradius-utils
        - ntp
      state: present
      update_cache: yes
    environment:
      DEBIAN_FRONTEND: noninteractive

  - name: create smb configuration file
    template:
      src: ./smb.conf.j2
      dest: /etc/samba/smb.conf
      owner: root
      group: root

  - name: create krb5 configuration file
    template:
      src: ./krb5.conf.j2
      dest: /etc/krb5.conf
      owner: root
      group: root  

  - name: Copy nsswitch.conf
    copy:
      src: ./nsswitch.conf
      dest: /etc/nsswitch.conf
      owner: root
      group: root

  - name: Add lint to hosts
    lineinfile:
      dest: /etc/hosts
      line: '{{ item }}'
    with_items:
      - "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}\t{{ ansible_hostname }}.{{ domain }}\t{{ ansible_hostname }}"

  - name: Remove lint from hosts
    lineinfile:
      path: /etc/hosts
      state: absent
      regexp: '^127.0.1.1'

#
#
# Bashсible! Mistrust...
  - name: Join to Domain
    shell: net ads join -U Administrator%{{ dc_admin_password }}
# Bashсible! Mistrust...
#
#
  - name: Restart winbind service
    service:
      name: winbind.service
      state: restarted

  - name: Enable winbind service
    service:
      name: winbind.service
      enabled: yes

  - name: create mschap configuration file
    template:
      src: ./mschap.j2
      dest: /etc/freeradius/3.0/mods-enabled/mschap
      owner: freerad
      group: freerad
      mode: 0640

  - name: create ntlm_auth configuration file
    template:
      src: ./ntlm_auth.j2
      dest: /etc/freeradius/3.0/mods-enabled/ntlm_auth
      owner: freerad
      group: freerad
      mode: 0640

  - name: create clients configuration file
    template:
      src: ./clients.conf.j2
      dest: /etc/freeradius/3.0/clients.conf
      owner: freerad
      group: freerad
      mode: 0640

  - name: adding freerad to group winbindd_priv
    user:
      name: freerad
      groups: winbindd_priv
      append: yes

  - name: Enable freeradius service
    service:
      name: freeradius.service
      enabled: yes

  - name: Restart freeradius service
    service:
      name: freeradius.service
      state: restarted
